# Generated by Django 5.0.13 on 2025-04-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='PRODUCT')),
                ('Name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Tên SP')),
                ('Price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá')),
                ('Introduce', models.TextField(blank=True, null=True, verbose_name='Giới thiệu')),
                ('Describe', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('Main_ingredients', models.TextField(blank=True, null=True, verbose_name='Thành phần chính')),
                ('How_use', models.TextField(blank=True, null=True, verbose_name='Cách sử dụng')),
                ('Ingredients_table', models.TextField(blank=True, null=True, verbose_name='Bảng thành phần')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['id'],
            },
        ),
    ]
