# Generated by Django 5.0.13 on 2025-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='PRODUCT')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='PRODUCT_AVATAR'),
        ),
    ]
