# Generated by Django 5.0.13 on 2025-04-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0003_photo_alter_product_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='Belong_Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_photo', to='sleekweb.product'),
        ),
    ]
