# Generated by Django 5.0.13 on 2025-04-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0006_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Danh mục'),
        ),
    ]
