# Generated by Django 5.0.13 on 2025-04-04 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0007_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_ncls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='PRODUCT_NCLS')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_photo_ncls', to='sleekweb.product')),
            ],
            options={
                'verbose_name_plural': 'Ảnh sản phẩm NCLS',
                'ordering': ['id'],
            },
        ),
    ]
