# Generated by Django 5.0.13 on 2025-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0008_photo_ncls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='PHOTO_CONTENT')),
                ('Content1', models.TextField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='PHOTO_CONTENT')),
                ('Content2', models.TextField(blank=True, null=True, verbose_name='Nội dung 2')),
                ('Photo3', models.ImageField(blank=True, null=True, upload_to='PHOTO_CONTENT')),
                ('Content3', models.TextField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Ảnh và Nội dung',
                'ordering': ['id'],
            },
        ),
    ]
