# Generated by Django 5.0.13 on 2025-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0009_photo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='PHOTO_SLIDER')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Ảnh Slider',
                'ordering': ['id'],
            },
        ),
    ]
