# Generated by Django 5.0.13 on 2025-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0010_photo_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='Price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá'),
        ),
    ]
