# Generated by Django 5.0.13 on 2025-04-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0011_size_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chi tiết SP'),
        ),
    ]
