# Generated by Django 5.0.13 on 2025-04-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0012_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Ingredients_table',
        ),
    ]
