# Generated by Django 5.0.13 on 2025-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0013_remove_product_ingredients_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_slider',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự xuất hiện'),
        ),
    ]
