# Generated by Django 5.0.13 on 2025-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0014_photo_slider_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Edit_Website')),
                ('Phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('Text_run', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chữ chạy')),
                ('Email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang web',
                'ordering': ['id'],
            },
        ),
    ]
