# Generated by Django 5.0.13 on 2025-04-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0016_edit_home_alter_website_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_ncls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nckh', models.ImageField(blank=True, null=True, upload_to='Edit_ncls')),
                ('Kqls', models.ImageField(blank=True, null=True, upload_to='Edit_ncls')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang ncls',
                'ordering': ['id'],
            },
        ),
    ]
