# Generated by Django 5.0.13 on 2025-04-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0018_edit_vct_edit_vct1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edit_vct1',
            old_name='Count',
            new_name='Order',
        ),
    ]
