# Generated by Django 5.0.13 on 2025-04-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0019_rename_count_edit_vct1_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_tnsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề')),
                ('Content', models.CharField(blank=True, null=True, verbose_name='Nội dung')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_vct')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin vct phần con',
                'ordering': ['id'],
            },
        ),
    ]
