# Generated by Django 5.0.13 on 2025-04-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0020_edit_tnsm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_tnsm',
        ),
    ]
