# Generated by Django 5.0.13 on 2025-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0021_delete_edit_tnsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_tnsm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 1')),
                ('Content1', models.CharField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='Edit_vct')),
                ('Title2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 2')),
                ('Title3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 2')),
                ('Content2', models.CharField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='Edit_vct')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang vct',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_tnsm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề')),
                ('Content', models.CharField(blank=True, null=True, verbose_name='Nội dung')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_vct')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin vct phần con',
                'ordering': ['id'],
            },
        ),
    ]
