# Generated by Django 5.0.13 on 2025-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0022_edit_tnsm_edit_tnsm1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_tnsm',
            name='Photo1',
            field=models.ImageField(blank=True, null=True, upload_to='Edit_tnsm'),
        ),
        migrations.AlterField(
            model_name='edit_tnsm',
            name='Photo2',
            field=models.ImageField(blank=True, null=True, upload_to='Edit_tnsm'),
        ),
        migrations.AlterField(
            model_name='edit_tnsm1',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Edit_tnsm'),
        ),
    ]
