# Generated by Django 5.0.13 on 2025-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0023_alter_edit_tnsm_photo1_alter_edit_tnsm_photo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_dsdt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên phòng khám')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_dsdt')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin tin tức, giải thưởng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_lh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ')),
                ('Link_map', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link map')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin map',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_ttgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_ttgt')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin tin tức, giải thưởng',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='edit_tnsm',
            options={'ordering': ['id'], 'verbose_name_plural': 'Thông tin trang tnsm'},
        ),
        migrations.AlterModelOptions(
            name='edit_tnsm1',
            options={'ordering': ['id'], 'verbose_name_plural': 'Thông tin tnsm phần con'},
        ),
        migrations.AlterField(
            model_name='edit_home',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='edit_tnsm',
            name='Title1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 1'),
        ),
        migrations.AlterField(
            model_name='edit_tnsm1',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='edit_vct',
            name='Title1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 1'),
        ),
        migrations.AlterField(
            model_name='edit_vct',
            name='Title2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 2'),
        ),
        migrations.AlterField(
            model_name='edit_vct1',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='website',
            name='Text_run',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chữ chạy'),
        ),
    ]
