# Generated by Django 5.0.13 on 2025-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0024_edit_dsdt_edit_lh_edit_ttgt_alter_edit_tnsm_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_dsdt',
        ),
        migrations.DeleteModel(
            name='Edit_lh',
        ),
        migrations.DeleteModel(
            name='Edit_ttgt',
        ),
    ]
