# Generated by Django 5.0.13 on 2025-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0026_edit_dsdt_edit_lh_edit_ttgt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edit_dsdt',
            options={'ordering': ['id'], 'verbose_name_plural': 'Danh sách đối tác'},
        ),
        migrations.AddField(
            model_name='edit_lh',
            name='Count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi'),
        ),
    ]
