# Generated by Django 5.0.13 on 2025-04-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0027_alter_edit_dsdt_options_edit_lh_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_dsdt',
        ),
    ]
