# Generated by Django 5.0.13 on 2025-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0028_delete_edit_dsdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_dsdt_mb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên phòng khám')),
                ('Address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ liên hệ')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_dsdt')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Danh sách đối tác',
                'ordering': ['id'],
            },
        ),
    ]
