# Generated by Django 5.0.13 on 2025-04-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0029_edit_dsdt_mb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_dsdt_mb',
        ),
    ]
