# Generated by Django 5.0.13 on 2025-04-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0031_edit_dsdt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_kqls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='Edit_kqls')),
                ('Title1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 1')),
                ('Content1', models.CharField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Title2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 2')),
                ('Content2', models.CharField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang kqls',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_nckh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='Edit_nckh')),
                ('Title1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 1')),
                ('Content1', models.CharField(blank=True, null=True, verbose_name='Nội dung 1')),
                ('Title2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 2')),
                ('Title3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiêu đề 2')),
                ('Photo2', models.ImageField(blank=True, null=True, upload_to='Edit_tnsm')),
                ('Content2', models.CharField(blank=True, null=True, verbose_name='Nội dung 3')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin trang nckh',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_nckh1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Content', models.CharField(blank=True, null=True, verbose_name='Nội dung')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_nckh')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin nckh phần con',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_nckh2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Content', models.CharField(blank=True, null=True, verbose_name='Nội dung')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_nckh')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin nckh phần con',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='edit_dsdt',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='edit_tnsm1',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='edit_ttgt',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='edit_vct1',
            name='Order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thứ tự'),
        ),
    ]
