# Generated by Django 5.0.13 on 2025-04-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0032_edit_kqls_edit_nckh_edit_nckh1_edit_nckh2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_nckh',
            name='Photo3',
            field=models.ImageField(blank=True, null=True, upload_to='Edit_tnsm'),
        ),
    ]
