# Generated by Django 5.0.13 on 2025-04-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0033_edit_nckh_photo3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_nckh',
        ),
    ]
