# Generated by Django 5.0.13 on 2025-04-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0035_edit_nckh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_ttgt',
        ),
    ]
