# Generated by Django 5.0.13 on 2025-04-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0036_delete_edit_ttgt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_ttgt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Photo1', models.ImageField(blank=True, null=True, upload_to='Edit_ttgt')),
                ('Count', models.IntegerField(blank=True, null=True, verbose_name='Số bản ghi')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin tin tức, giải thưởng',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Edit_ttgt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề')),
                ('Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Danh mục')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Edit_ttgt')),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'verbose_name_plural': 'Thông tin tin tức, giải thưởng',
                'ordering': ['id'],
            },
        ),
    ]
