# Generated by Django 5.0.13 on 2025-04-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0037_edit_ttgt_edit_ttgt1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_lh',
            name='Link_map',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Link map'),
        ),
    ]
