# Generated by Django 5.0.13 on 2025-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0038_alter_edit_lh_link_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_nckh',
            name='Title2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 2'),
        ),
        migrations.AlterField(
            model_name='edit_nckh',
            name='Title3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiêu đề 2'),
        ),
    ]
