# Generated by Django 5.0.13 on 2025-04-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0039_alter_edit_nckh_title2_alter_edit_nckh_title3'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_dsdt',
            name='Link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link'),
        ),
    ]
