# Generated by Django 5.0.13 on 2025-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0041_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
