# Generated by Django 5.0.13 on 2025-04-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0042_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='AVATAR_BLOG'),
        ),
    ]
