# Generated by Django 5.0.13 on 2025-04-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0043_blogpost_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
