# Generated by Django 5.0.13 on 2025-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0044_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Title',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
