# Generated by Django 5.0.13 on 2025-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0045_alter_blogpost_slug_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
