# Generated by Django 5.0.13 on 2025-04-25 02:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0046_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_ttgt1',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
