# Generated by Django 5.0.13 on 2025-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0047_edit_ttgt1_content_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='edit_ttgt1',
            name='Slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
