# Generated by Django 5.0.13 on 2025-05-21 09:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0048_edit_ttgt1_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_kqls1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Order', models.IntegerField(blank=True, null=True, verbose_name='Thứ tự')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
    ]
