# Generated by Django 5.0.13 on 2025-05-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0049_edit_kqls1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edit_kqls1',
            name='Slug',
        ),
    ]
