# Generated by Django 5.0.13 on 2025-06-17 09:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0050_remove_edit_kqls1_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='KqlsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=350, null=True)),
                ('Slug', models.SlugField(blank=True, max_length=350, null=True, unique=True)),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='AVATAR_KQLS')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
    ]
