# Generated by Django 5.2.7 on 2026-03-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0052_seo_home"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seo_KQLS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seo_LH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seo_NCKH",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seo_TNSM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seo_TTGT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Seo_VCT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
    ]
