# Generated by Django 5.2.7 on 2026-03-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0053_seo_kqls_seo_lh_seo_nckh_seo_tnsm_seo_ttgt_seo_vct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seo_Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Seo_Title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "Seo_Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("Name_Page", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "Creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian tạo"
                    ),
                ),
                (
                    "Update_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Seo_Home",
        ),
        migrations.DeleteModel(
            name="Seo_KQLS",
        ),
        migrations.DeleteModel(
            name="Seo_LH",
        ),
        migrations.DeleteModel(
            name="Seo_NCKH",
        ),
        migrations.DeleteModel(
            name="Seo_TNSM",
        ),
        migrations.DeleteModel(
            name="Seo_TTGT",
        ),
        migrations.DeleteModel(
            name="Seo_VCT",
        ),
    ]
