# Generated by Django 5.2.7 on 2026-03-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0054_seo_page_delete_seo_home_delete_seo_kqls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Seo_Description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="Seo_Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
