# Generated by Django 5.2.7 on 2026-03-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0056_blogpost_seo_description_blogpost_seo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="kqlspost",
            name="Seo_Description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="kqlspost",
            name="Seo_Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
