# Generated by Django 5.2.7 on 2026-03-04 08:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0057_kqlspost_seo_description_kqlspost_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Describe",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
