# Generated by Django 5.2.7 on 2026-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0058_alter_product_describe"),
    ]

    operations = [
        migrations.AddField(
            model_name="edit_ttgt1",
            name="Seo_Description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="edit_ttgt1",
            name="Seo_Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
