# Generated by Django 5.2.7 on 2026-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0059_edit_ttgt1_seo_description_edit_ttgt1_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo_content",
            name="Photo3",
            field=models.FileField(blank=True, null=True, upload_to="PHOTO_CONTENT"),
        ),
    ]
