# Generated by Django 5.2.7 on 2026-04-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sleekweb", "0060_alter_photo_content_photo3"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Cosbeauty_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Link Cosbeauty"
            ),
        ),
    ]
